name: pynguin-for-ML-libraries

dependencies:
  - python=3.10.14
  - pip=23.3.1
  - pip:
    - matplotlib==3.8.4
    - matplotlib-venn==0.11.10
    - PyLaTeX==1.4.2
    - scipy==1.13.0
    - coverage==7.5.1
    - -e ./pynguin

variables:
  PYNGUIN_DANGER_AWARE: 1
